[project]
authors = ["kklein </>"]
channels = ["conda-forge"]
name = "payslips"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.2,<3.14"
pypdf = ">=5.3.1,<6"
ipython = ">=9.0.2,<10"
click = ">=8.1.8,<9"
ipdb = ">=0.13.13,<0.14"
git_root = ">=0.2,<0.3"
cryptography = ">=44.0.2,<45"
google-api-python-client = ">=2.163.0,<3"
google-auth-httplib2 = ">=0.2.0,<0.3"
google-auth-oauthlib = ">=1.2.1,<2"
ruff = ">=0.9.10,<0.10"
mypy = ">=1.15.0,<2"
isort = ">=6.0.1,<7"
